/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.56
 * Generated at: 2022-03-29 02:56:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class contact_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(11);
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-4.2.13.RELEASE.jar", Long.valueOf(1646873798857L));
    _jspx_dependants.put("jar:file:/D:/EzenClass/05_Spring-workspace/apache-tomcat-9.0.56/wtpwebapps/ezenMini/WEB-INF/lib/jstl-1.2.jar!/META-INF/x.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/nav.jsp", Long.valueOf(1648168922596L));
    _jspx_dependants.put("/WEB-INF/views/footer.jsp", Long.valueOf(1647230866707L));
    _jspx_dependants.put("jar:file:/D:/EzenClass/05_Spring-workspace/apache-tomcat-9.0.56/wtpwebapps/ezenMini/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/EzenClass/05_Spring-workspace/apache-tomcat-9.0.56/wtpwebapps/ezenMini/WEB-INF/lib/spring-security-taglibs-4.2.13.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1560936316000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1644909417825L));
    _jspx_dependants.put("jar:file:/D:/EzenClass/05_Spring-workspace/apache-tomcat-9.0.56/wtpwebapps/ezenMini/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/EzenClass/05_Spring-workspace/apache-tomcat-9.0.56/wtpwebapps/ezenMini/WEB-INF/lib/jstl-1.2.jar!/META-INF/sql.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/EzenClass/05_Spring-workspace/apache-tomcat-9.0.56/wtpwebapps/ezenMini/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/carousel.jsp", Long.valueOf(1647311162626L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write(" \r\n");
      out.write("   \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta id=\"_csrf\" name=\"_csrf\" content=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/b4e02812b5.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("html, body {\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#main {\r\n");
      out.write("	height: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#search-panel {\r\n");
      out.write("	width: 65%;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	top: 60px;\r\n");
      out.write("	z-index: 5;\r\n");
      out.write("	background-color: #FFF;\r\n");
      out.write("	padding: 5px;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#address {\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#google-map {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 600px;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write(" \r\n");
      out.write("   \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/b4e02812b5.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<!-- \r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("-->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write(".navbar {\r\n");
      out.write("	border-radius: 0;\r\n");
      out.write("	margin-bottom: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-link {\r\n");
      out.write("	font-weight: 400;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#searchForm {\r\n");
      out.write("	visibility: hidden;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<nav class=\"navbar navbar-expand-md bg-dark navbar-dark fixed-top font-weight-bold\">\r\n");
      out.write("	<a href=\"/mini\" class=\"navbar-brand\">\r\n");
      out.write("		<i class=\"fa-solid fa-c fa-bounce\"></i>\r\n");
      out.write("		<i class=\"fa-solid fa-a fa-bounce\"></i>\r\n");
      out.write("		<i class=\"fa-solid fa-r fa-bounce\"></i>\r\n");
      out.write("		<i class=\"fa-solid fa-l fa-bounce\"></i>\r\n");
      out.write("		<i class=\"fa-solid fa-h fa-bounce\"></i>\r\n");
      out.write("		<i class=\"fa-solid fa-a fa-bounce\"></i>\r\n");
      out.write("		<i class=\"fa-solid fa-r fa-bounce\"></i>\r\n");
      out.write("		<i class=\"fa-solid fa-r fa-bounce\"></i>\r\n");
      out.write("		<i class=\"fa-solid fa-t fa-bounce\"></i>\r\n");
      out.write("	</a>\r\n");
      out.write("	\r\n");
      out.write("	<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#collapsibleNavbar\">\r\n");
      out.write("		<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("	</button>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"collapse navbar-collapse\" id=\"collapsibleNavbar\">\r\n");
      out.write("		<ul class=\"navbar-nav\">\r\n");
      out.write("			<li class=\"nav-item\">\r\n");
      out.write("				<a href=\"home\" class=\"nav-link\">Home</a>\r\n");
      out.write("			</li>\r\n");
      out.write("		\r\n");
      out.write("			<li class=\"nav-item\">\r\n");
      out.write("				<a href=\"product\" class=\"nav-link\">Products</a>\r\n");
      out.write("			</li>\r\n");
      out.write("			\r\n");
      out.write("			<li class=\"nav-item\">\r\n");
      out.write("				<a href=\"util\" class=\"nav-link\">Utils</a>\r\n");
      out.write("			</li>\r\n");
      out.write("			\r\n");
      out.write("			<li class=\"nav-item\">\r\n");
      out.write("				<a href=\"stores\" class=\"nav-link\">Stores</a>\r\n");
      out.write("			</li>\r\n");
      out.write("			\r\n");
      out.write("			<li class=\"nav-item\">\r\n");
      out.write("				<a href=\"contact\" class=\"nav-link\">Contact</a>\r\n");
      out.write("			</li>\r\n");
      out.write("			\r\n");
      out.write("			<li class=\"nav-item\">\r\n");
      out.write("				<a href=\"folio\" class=\"nav-link\">Portfolio</a>\r\n");
      out.write("			</li>\r\n");
      out.write("			\r\n");
      out.write("			<li class=\"nav-item\">\r\n");
      out.write("				<a href=\"dash\" class=\"nav-link\">Dash</a>\r\n");
      out.write("			</li>\r\n");
      out.write("			\r\n");
      out.write("			<!-- Dropdown -->\r\n");
      out.write("			<li class=\"nav-item dropdown\">\r\n");
      out.write("				<a href=\"#\" class=\"nav-link dropdown-toggle\" id=\"navbardrop\" data-toggle=\"dropdown\">알림</a>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"dropdown-menu\">\r\n");
      out.write("					<a href=\"notice\" class=\"dropdown-item\">공지사항</a>\r\n");
      out.write("					<a href=\"board\" class=\"dropdown-item\">게시판</a>\r\n");
      out.write("					<a href=\"qna\" class=\"dropdown-item\">Q&A</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</li>\r\n");
      out.write("			\r\n");
      out.write("			<li class=\"nav-item\">\r\n");
      out.write("				<a href=\"#\" class=\"nav-link btn disabled\">Space</a>\r\n");
      out.write("			</li>\r\n");
      out.write("			\r\n");
      out.write("			<li class=\"nav-item\">\r\n");
      out.write("				<a href=\"login_view\" class=\"nav-link\">Login</a>\r\n");
      out.write("			</li>\r\n");
      out.write("			\r\n");
      out.write("			<li class=\"nav-item\">\r\n");
      out.write("				<a href=\"logout_view\" class=\"nav-link\">Logout</a>\r\n");
      out.write("			</li>\r\n");
      out.write("			\r\n");
      out.write("			<li class=\"nav-item\">\r\n");
      out.write("				<a href=\"join_view\" class=\"nav-link\">Join</a>\r\n");
      out.write("			</li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<form action=\"#\" id=\"searchForm\" class=\"form-inline\">\r\n");
      out.write("		<button class=\"btn btn-primary mr-sm-2\" type=\"button\" disabled>\r\n");
      out.write("			<i class=\"fa fa-search\"></i>\r\n");
      out.write("		</button>\r\n");
      out.write("		<input type=\"text\" id=\"searchInput\" class=\"form-control mr-sm-2\" placeholder=\"Search\"/>\r\n");
      out.write("	</form>\r\n");
      out.write("\r\n");
      out.write("</nav>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write(" \r\n");
      out.write("   \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/b4e02812b5.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<!-- \r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("-->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("html, body {\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#demo {\r\n");
      out.write("	margin-top: 3.7rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 이미지 크기만큼 지정해주는 것이 좋음 */\r\n");
      out.write(".carousel-inner img {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 400px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("														   <!-- 슬라이드되는 ms 지정 (default : 5s)-->\r\n");
      out.write("<div id=\"demo\" class=\"carousel slide mb-5\" data-ride=\"carousel\" data-interval=\"6000\">\r\n");
      out.write("	<ul class=\"carousel-indicators\">\r\n");
      out.write("		<!-- data-target : 슬라이드 이미지가 보여질 박스 지정 , data-slide-to : 몇번째 슬라이드인지 지정 , active : 현재 보여지고 있는 이미지 li -->\r\n");
      out.write("		<li data-target=\"#demo\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("		<li data-target=\"#demo\" data-slide-to=\"1\"></li>\r\n");
      out.write("		<li data-target=\"#demo\" data-slide-to=\"2\"></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("	\r\n");
      out.write("	<!-- 각각의 이미지가 담긴 박스 -->\r\n");
      out.write("	<div class=\"carousel-inner\">\r\n");
      out.write("		<div class=\"carousel-item active\">\r\n");
      out.write("			<img src=\"images/4.jpg\" alt=\"glasses\" width=\"1100\" height=\"500\" />\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"carousel-item text-dark\">\r\n");
      out.write("			<img src=\"images/5.jpg\" alt=\"shirt\" width=\"1100\" height=\"500\" />\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"carousel-item text-dark\">\r\n");
      out.write("			<img src=\"images/6.jpg\" alt=\"tee\" width=\"1100\" height=\"500\" />\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<a href=\"#demo\" class=\"carousel-control-prev\" data-slide=\"prev\">\r\n");
      out.write("		<span class=\"carousel-control-prev-icon text-dark\"></span>\r\n");
      out.write("	</a>\r\n");
      out.write("		<a href=\"#demo\" class=\"carousel-control-next\" data-slide=\"next\">\r\n");
      out.write("		<span class=\"carousel-control-next-icon text-dark\"></span>\r\n");
      out.write("	</a>\r\n");
      out.write("	\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"main\" class=\"container mt-5\">\r\n");
      out.write("	<h3 class=\"display-4 font-italic\">Contact</h3>\r\n");
      out.write("	<div id=\"search-panel\">");
      out.write("	\r\n");
      out.write("		<input type=\"text\" id=\"address\" placeholder=\"주소를 입력하세요\" size=\"70px\" class=\"border\" autofocus=\"autofocus\"/>\r\n");
      out.write("		<button type=\"button\" id=\"submit\" class=\"btn btn-primary\" value=\"Geocode\">지도 검색</button>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("	<div id=\"google-map\" class=\"mx-auto mb-5\"></div>\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("	<div class=\"row\">\r\n");
      out.write("		<div class=\"d-flex col-4 flex-column\">\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"d-flex flex-row\">\r\n");
      out.write("				<div>\r\n");
      out.write("					<i class=\"fa fa-home\" aria-hidden=\"true\"></i>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<h5>Binghamton, New York</h5>\r\n");
      out.write("					<p>\r\n");
      out.write("						4343 Hinkle Deegan Lake Road\r\n");
      out.write("					</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("	\r\n");
      out.write("			<div class=\"d-flex flex-row\">\r\n");
      out.write("				<div>\r\n");
      out.write("					<i class=\"fa fa-headphones\" aria-hidden=\"true\"></i>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<h5>00 (958) 9865 562</h5>\r\n");
      out.write("					<p>Mon to Fri 9am to 6 pm</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"d-flex flex-row\">\r\n");
      out.write("				<div>\r\n");
      out.write("					<i class=\"fa fa-envelope\" aria-hidden=\"true\"></i>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<h5>support@colorlib.com</h5>\r\n");
      out.write("					<p>Send us your query anytime!</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"col-8\">\r\n");
      out.write("			<form class=\"text-right\" id=\"myForm\" action=\"\" method=\"post\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-6 form-group\">\r\n");
      out.write("						<input name=\"name\" placeholder=\"Enter your name\" onfocus=\"this.placeholder = ''\"\r\n");
      out.write("							onblur=\"this.placeholder = 'Enter your name'\" class=\"mb-20 form-control\" type=\"text\">\r\n");
      out.write("						<input name=\"email\" placeholder=\"Enter email address\" pattern=\"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{1,63}$\"\r\n");
      out.write("							 onfocus=\"this.placeholder = ''\" onblur=\"this.placeholder = 'Enter email address'\" class=\"mb-20 form-control\"\r\n");
      out.write("							 type=\"email\">\r\n");
      out.write("						<input name=\"subject\" placeholder=\"Enter subject\" onfocus=\"this.placeholder = ''\" onblur=\"this.placeholder = 'Enter subject'\"\r\n");
      out.write("							 class=\"mb-20 form-control\" type=\"text\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-6 form-group\">\r\n");
      out.write("						<textarea class=\"form-control\" name=\"message\" placeholder=\"Enter Messege\" onfocus=\"this.placeholder = ''\"\r\n");
      out.write("							 onblur=\"this.placeholder = 'Enter Messege'\" rows=\"5\"></textarea>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-12\">\r\n");
      out.write("						<div style=\"text-align: left;\"></div>\r\n");
      out.write("						<button class=\"btn btn-primary\" style=\"float: right;\">Send Message</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write(" \r\n");
      out.write("   \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/b4e02812b5.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<!-- \r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("-->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("footer {\r\n");
      out.write("	height: auto;\r\n");
      out.write("	background-color: #f2f2f2;\r\n");
      out.write("	padding: 25px;	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-title {\r\n");
      out.write("	font-style: italic;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<footer class=\"mt-5\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<h6 class=\"text-center display-4 footer-title mb-3\">Online Store Copyright</h6>\r\n");
      out.write("\r\n");
      out.write("		<form action=\"#\" method=\"post\" class=\"footer-frm row\">\r\n");
      out.write("			<div class=\"formgroup col-11\">\r\n");
      out.write("				<label for=\"email\">&nbsp;&nbsp;Get deals</label>\r\n");
      out.write("				<input type=\"text\" class=\"form-control\" id=\"email\" placeholder=\"Enter email\" />\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<button type=\"submit\" class=\"btn btn-danger col-1\">Sing Up</button>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("// Google Map API 주소의 callback 함수\r\n");
      out.write("function initMap() {\r\n");
      out.write("	console.log('Map is initialized.');\r\n");
      out.write("	\r\n");
      out.write("	let map;\r\n");
      out.write("	\r\n");
      out.write("	getLocation();\r\n");
      out.write("	\r\n");
      out.write("	function getLocation() {\r\n");
      out.write("		if( navigator.geolocation ) {\r\n");
      out.write("			navigator.geolocation.watchPosition(showPosition);\r\n");
      out.write("		} else {\r\n");
      out.write("			map = $('#google-map');\r\n");
      out.write("			map.text('Geolocation is not supported by this browser');\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		function showPosition(position) {\r\n");
      out.write("			lati = position.coords.latitude;\r\n");
      out.write("			longi = position.coords.longitude;\r\n");
      out.write("			\r\n");
      out.write("			map = new google.maps.Map(document.getElementById('google-map'), {\r\n");
      out.write("				zoom: 16,\r\n");
      out.write("				center: new google.maps.LatLng(lati, longi)\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			var marker = new google.maps.Marker({\r\n");
      out.write("				position: new google.maps.LatLng(lati, longi),\r\n");
      out.write("				map: map,\r\n");
      out.write("				title: 'hello, world'\r\n");
      out.write("			});\r\n");
      out.write("		};\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		var geocoder = new google.maps.Geocoder();\r\n");
      out.write("		\r\n");
      out.write("		document.getElementById('submit').addEventListener('click', function() {\r\n");
      out.write("			console.log('submit 버튼 클릭 이벤트 실행');\r\n");
      out.write("			geocodeAddress(geocoder, map);\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		function geocodeAddress(geocoder, resultMap) {\r\n");
      out.write("			console.log('geocodeAddress 함수 실행');\r\n");
      out.write("			let address = document.getElementById('address').value;\r\n");
      out.write("\r\n");
      out.write("			//입력받은 주소로 좌표에 맵 마커를 생성\r\n");
      out.write("			geocoder.geocode({'address' : address}, function(result, status) {\r\n");
      out.write("														console.log('result : ' + result + \" / \" + \"status : \" + status);\r\n");
      out.write("														\r\n");
      out.write("														if ( status === 'OK' ) {\r\n");
      out.write("																													\r\n");
      out.write("															resultMap.setCenter(result[0].geometry.location);\r\n");
      out.write("															resultMap.setZoom(18);\r\n");
      out.write("															\r\n");
      out.write("															var marker = new google.maps.Marker({\r\n");
      out.write("																map: resultMap,\r\n");
      out.write("																position: result[0].geometry.location\r\n");
      out.write("															});\r\n");
      out.write("															\r\n");
      out.write("															console.log('위도(latitude) : ' + marker.postion.lat());\r\n");
      out.write("															console.log('위도(longitude) : ' + marker.postion.lng());\r\n");
      out.write("														} else {\r\n");
      out.write("															alert('검색 결과가 없습니다.');\r\n");
      out.write("														}\r\n");
      out.write("														\r\n");
      out.write("													 });\r\n");
      out.write("		};\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script async defer src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyCl3troictldoLX7-RsH7NiFiGVzUWGgv8&callback=initMap&v=weekly&channel=2\">\r\n");
      out.write("\r\n");
      out.write("/* \r\n");
      out.write(" * async와 defer는 백그라운드에서 다운로드를 하여 html 파싱을 방해하지 않으나 defer는 외부 script만 제한\r\n");
      out.write(" * defer는 파싱 종료시까지 실행을 멈추나 async는 실행시에는 html 파싱이 멈춤\r\n");
      out.write(" * 두개를 동시에 사용하여 트 실행을 멈춤\r\n");
      out.write(" */\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
